import Link from "next/link";
import { AtlasSiteShell, SitePageHero } from "../../components/site/AtlasSiteShell";

const OFFERS=[
["Individuel","Accès personnel","Conversation ATLAS, parcours guidés, préférences et continuité de session. La tarification définitive sera activée uniquement après validation commerciale."],
["Professionnel","Accompagnement augmenté","Pour les professionnels souhaitant utiliser ATLAS comme couche d’orientation, de préparation ou de continuité, sans substitution à leur pratique."],
["Organisation","Déploiement encadré","Pour entreprises, écoles, institutions ou partenaires avec gouvernance, politiques d’accès, reporting agrégé et exigences de sécurité renforcées."],
] as const;
export default function OffersPage(){return <AtlasSiteShell><SitePageHero eyebrow="OFFRES" title="Une plateforme. Plusieurs niveaux d’usage." lead="ATLAS est pensé pour servir une personne seule comme une organisation, avec des droits, des limites et une gouvernance adaptés au contexte. Les offres commerciales restent en préproduction privée tant que les validations juridiques, financières et de sécurité ne sont pas terminées." actions={<><Link className="site-primary-button" href="/conversation">Tester ATLAS</Link><Link className="site-link-button" href="/connexion">Espace privé</Link></>}/><section className="site-section site-section-tight"><div className="site-pricing">{OFFERS.map(([name,label,desc],i)=><article className={`site-price-card${i===1?" featured":""}`} key={name}><p className="site-eyebrow">{name}</p><h3>{label}</h3><strong>Sur validation</strong><p>{desc}</p><ul><li>Accès sécurisé</li><li>Contrôle du consentement</li><li>Expérience adaptée au rôle</li><li>Pas d’engagement commercial actif en préproduction</li></ul></article>)}</div></section><section className="site-band"><div><p className="site-eyebrow">PRÉPRODUCTION</p><h2>Aucun paiement réel n’est ouvert sur cette version privée.</h2><p>Les connecteurs Stripe et PayPal restent en environnement sandbox jusqu’à validation explicite de l’entité juridique, des conditions, de la politique de confidentialité et du passage en production.</p></div><Link className="site-primary-button" href="/confiance">Voir la gouvernance</Link></section></AtlasSiteShell>}
