const STORAGE_KEY='atlas_ecosystem_state_v2';
const CHAT_KEY='atlas_chat_v1';
const defaults={intent:null,emotion:null,intensity:6,context:null,afterIntensity:null,completedBreath:false,lastPage:'accueil',motion:'auto',localMemory:true,completedResources:[],updatedAt:null};
const loadState=()=>{try{return {...defaults,...JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}')}}catch{return {...defaults}}};
const saveState=(patch={})=>{const next={...loadState(),...patch,updatedAt:new Date().toISOString()};localStorage.setItem(STORAGE_KEY,JSON.stringify(next));return next};
let state=loadState();
const body=document.body;
const systemReduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const reduced=systemReduced||state.motion==='reduced';
if(reduced)body.dataset.motion='reduced';
const root=document.documentElement;
const boot=document.querySelector('[data-boot]');
const ready=()=>setTimeout(()=>boot?.classList.add('done'),280);
if(document.readyState==='complete')ready();else addEventListener('load',ready,{once:true});setTimeout(ready,1900);

const transition=document.createElement('div');transition.className='page-transition';document.body.appendChild(transition);
document.addEventListener('click',event=>{const link=event.target.closest('a[href]');if(!link||event.defaultPrevented||link.target==='_blank'||link.hasAttribute('download'))return;const url=new URL(link.href,location.href);if(url.origin!==location.origin||url.hash&&url.pathname===location.pathname)return;event.preventDefault();transition.classList.add('active');setTimeout(()=>location.href=url.href,260)});
addEventListener('pageshow',()=>transition.classList.remove('active'));

addEventListener('pointermove',e=>{root.style.setProperty('--mx',`${e.clientX}px`);root.style.setProperty('--my',`${e.clientY}px`)},{passive:true});
const updateScroll=()=>{const max=Math.max(1,document.documentElement.scrollHeight-innerHeight);root.style.setProperty('--scroll',Math.min(1,scrollY/max).toFixed(4));document.querySelector('[data-header]')?.classList.toggle('scrolled',scrollY>80)};
addEventListener('scroll',updateScroll,{passive:true});updateScroll();
document.querySelector('[data-menu]')?.addEventListener('click',e=>{const h=document.querySelector('[data-header]');const open=h.classList.toggle('menu-open');e.currentTarget.setAttribute('aria-expanded',String(open))});
document.querySelectorAll('[data-header] nav a').forEach(a=>a.addEventListener('click',()=>document.querySelector('[data-header]')?.classList.remove('menu-open')));

const revealObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting)entry.target.classList.add('visible')}),{threshold:.12,rootMargin:'0px 0px -5% 0px'});
document.querySelectorAll('.reveal').forEach(el=>revealObserver.observe(el));

const canvas=document.querySelector('[data-atlas-scene]');
if(canvas){const ctx=canvas.getContext('2d',{alpha:true});let nodes=[],raf=0,last=0,speed=1;
  const palettes={home:['79,141,125','200,162,97'],start:['79,141,125','143,199,181'],understand:['79,141,125','196,240,222'],calm:['143,199,181','225,197,141'],human:['200,162,97','242,214,170'],chat:['79,141,125','196,240,222'],evolve:['79,141,125','225,197,141'],resources:['79,141,125','143,199,181'],account:['79,141,125','200,162,97'],emergency:['216,132,115','242,214,170']};
  const colors=palettes[body.dataset.scene]||palettes.home;
  const resize=()=>{const dpr=Math.min(devicePixelRatio||1,innerWidth<700?1.2:1.6);canvas.width=Math.floor(innerWidth*dpr);canvas.height=Math.floor(innerHeight*dpr);canvas.style.width=`${innerWidth}px`;canvas.style.height=`${innerHeight}px`;ctx.setTransform(dpr,0,0,dpr,0,0);const count=innerWidth<700?25:Math.min(92,Math.round(innerWidth/21));nodes=Array.from({length:count},(_,i)=>({x:Math.random()*innerWidth,y:Math.random()*innerHeight,vx:(Math.random()-.5)*.16,vy:(Math.random()-.5)*.16,r:Math.random()*1.3+.3,phase:Math.random()*6.28,c:i%2}))};
  const draw=t=>{if(document.hidden||reduced)return;if(t-last<28){raf=requestAnimationFrame(draw);return}last=t;ctx.clearRect(0,0,innerWidth,innerHeight);for(let i=0;i<nodes.length;i++){const n=nodes[i];n.x+=n.vx*speed;n.y+=n.vy*speed;n.phase+=.008*speed;if(n.x<-20)n.x=innerWidth+20;if(n.x>innerWidth+20)n.x=-20;if(n.y<-20)n.y=innerHeight+20;if(n.y>innerHeight+20)n.y=-20;ctx.beginPath();ctx.arc(n.x,n.y,n.r*(1+Math.sin(n.phase)*.25),0,Math.PI*2);ctx.fillStyle=`rgba(${colors[n.c]},.34)`;ctx.fill();for(let j=i+1;j<nodes.length;j++){const m=nodes[j],dx=n.x-m.x,dy=n.y-m.y,d=Math.hypot(dx,dy);if(d<130){ctx.beginPath();ctx.moveTo(n.x,n.y);ctx.lineTo(m.x,m.y);ctx.strokeStyle=`rgba(${colors[(n.c+m.c)%2]},${(1-d/130)*.075})`;ctx.lineWidth=.55;ctx.stroke()}}}raf=requestAnimationFrame(draw)};
  resize();addEventListener('resize',resize,{passive:true});if(!reduced)raf=requestAnimationFrame(draw);window.atlasScene={setSpeed:v=>speed=v};
}

if(!reduced&&matchMedia('(pointer:fine)').matches){document.querySelectorAll('.magnetic').forEach(el=>{el.addEventListener('pointermove',e=>{const r=el.getBoundingClientRect();el.style.transform=`translate(${(e.clientX-r.left-r.width/2)*.07}px,${(e.clientY-r.top-r.height/2)*.07}px)`});el.addEventListener('pointerleave',()=>el.style.transform='')})}
const toast=document.querySelector('[data-toast]');let toastTimer;const showToast=msg=>{if(!toast)return;clearTimeout(toastTimer);toast.textContent=msg;toast.classList.add('visible');toastTimer=setTimeout(()=>toast.classList.remove('visible'),3300)};

// Entry route.
document.querySelectorAll('[data-intent]').forEach(btn=>btn.addEventListener('click',()=>{const intent=btn.dataset.intent;saveState({intent,lastPage:'commencer'});if(intent==='apaiser')location.href='apaiser.html';else if(intent==='parler')location.href='parler-a-atlas.html';else location.href='comprendre.html'}));

// Understand.
let selectedEmotion=state.emotion;let selectedContext=state.context;const intensity=document.getElementById('intensity');const intensityOutput=document.getElementById('intensity-output');const result=document.querySelector('[data-clarity-result]');const toCalm=document.querySelector('[data-to-calm]');
if(intensity){intensity.value=String(state.intensity||6);intensityOutput.textContent=`${intensity.value}/10`;intensity.addEventListener('input',()=>{intensityOutput.textContent=`${intensity.value}/10`;state=saveState({intensity:Number(intensity.value)})})}
const refreshClarity=()=>{document.querySelectorAll('[data-emotion]').forEach(n=>n.classList.toggle('selected',n.dataset.emotion===selectedEmotion));document.querySelectorAll('[data-context]').forEach(n=>n.classList.toggle('selected',n.dataset.context===selectedContext));if(result){result.textContent=selectedEmotion?selectedEmotion==='Je ne sais pas'?'Vous n’avez pas besoin du mot parfait. Nous pouvons commencer sans étiquette.':`Vous avez indiqué « ${selectedEmotion.toLowerCase()} »${selectedContext?` dans un contexte lié à ${selectedContext.toLowerCase()}`:''}. Souhaitez-vous d’abord diminuer son intensité ?`:'Sélectionnez un ressenti pour continuer.'}if(toCalm)toCalm.disabled=!selectedEmotion};
document.querySelectorAll('[data-emotion]').forEach(btn=>btn.addEventListener('click',()=>{selectedEmotion=btn.dataset.emotion;state=saveState({emotion:selectedEmotion,intensity:Number(intensity?.value||6),lastPage:'comprendre'});refreshClarity()}));
document.querySelectorAll('[data-context]').forEach(btn=>btn.addEventListener('click',()=>{selectedContext=selectedContext===btn.dataset.context?null:btn.dataset.context;state=saveState({context:selectedContext});refreshClarity()}));
toCalm?.addEventListener('click',()=>location.href='apaiser.html');refreshClarity();

// Calm.
const calmIntro=document.querySelector('[data-calm-intro]');if(calmIntro&&state.emotion)calmIntro.textContent=`Vous avez indiqué « ${state.emotion.toLowerCase()} » à ${state.intensity}/10. La lumière, les synapses et la profondeur vont maintenant suivre un rythme plus lent.`;
const breathStart=document.querySelector('[data-breath-start]');const breathPhase=document.querySelector('[data-breath-phase]');const breathSeconds=document.querySelector('[data-breath-seconds]');const breathCaption=document.querySelector('[data-breath-caption]');const afterCheck=document.querySelector('[data-after-check]');let remaining=60,breathing=false,timer=null,phaseTimer=null;
const stopBreath=(done=false)=>{clearInterval(timer);clearInterval(phaseTimer);timer=phaseTimer=null;breathing=false;body.classList.remove('breathing-in');window.atlasScene?.setSpeed(1);if(breathStart)breathStart.innerHTML='Lancer 60 secondes <span>→</span>';if(breathPhase)breathPhase.textContent='Prêt';if(breathSeconds)breathSeconds.textContent='60';if(breathCaption)breathCaption.textContent='Respiration cohérente';remaining=60;if(done&&afterCheck){afterCheck.hidden=false;state=saveState({completedBreath:true,lastPage:'apaiser'});afterCheck.scrollIntoView({behavior:reduced?'auto':'smooth',block:'center'})}};
breathStart?.addEventListener('click',()=>{if(breathing){stopBreath();return}breathing=true;breathStart.textContent='Arrêter';window.atlasScene?.setSpeed(.35);const phases=[['Inspirez',4,true,'Laissez l’espace s’ouvrir'],['Expirez',6,false,'Relâchez sans forcer'],['Restez',2,false,'Restez simplement présent']];let i=0,elapsed=0;const setPhase=()=>{const [name,,inhale,caption]=phases[i];breathPhase.textContent=name;breathCaption.textContent=caption;body.classList.toggle('breathing-in',inhale)};setPhase();timer=setInterval(()=>{remaining--;breathSeconds.textContent=String(remaining);if(remaining<=0){stopBreath(true);showToast('Séquence terminée. Prenez un instant avant de continuer.')}},1000);phaseTimer=setInterval(()=>{elapsed++;if(elapsed>=phases[i][1]){i=(i+1)%phases.length;elapsed=0;setPhase()}},1000)});
const afterIntensity=document.getElementById('after-intensity');const afterOutput=document.getElementById('after-output');afterIntensity?.addEventListener('input',()=>afterOutput.textContent=`${afterIntensity.value}/10`);document.querySelector('[data-save-after]')?.addEventListener('click',()=>{const value=Number(afterIntensity.value);state=saveState({afterIntensity:value});const diff=(state.intensity||6)-value;document.querySelector('[data-after-result]').textContent=diff>0?`Vous avez déclaré une baisse de ${diff} point${diff>1?'s':''}. Vous pouvez poursuivre doucement ou rejoindre une présence humaine.`:'Votre ressenti reste présent. Le relais humain reste accessible sans terminer d’autre étape.';showToast('Ressenti enregistré localement.')});

// Human relay.
const humanStatus=document.querySelector('[data-human-status]');if(humanStatus&&state.emotion)humanStatus.textContent=`Dernier ressenti déclaré : ${state.emotion}, ${state.intensity}/10${state.afterIntensity!=null?` puis ${state.afterIntensity}/10 après l’exercice`:''}.`;
const humanDialog=document.querySelector('[data-human-dialog]');const humanTitle=document.querySelector('[data-dialog-title]');const humanCopy=document.querySelector('[data-dialog-copy]');const copyByAction={proche:'ATLAS peut vous aider à formuler un message simple pour demander une présence, un appel ou un rendez-vous à une personne de confiance.',professionnel:'Cette option sera reliée à un annuaire vérifié de professionnels, avec leurs qualifications, disponibilités, zones d’intervention et conditions de prise en charge.',partenaire:'Le futur réseau ATLAS présentera clairement les structures partenaires, leurs spécialités, leurs horaires et le mode de prise de contact.',urgence:'Les ressources urgentes françaises sont disponibles sur la page Aide urgente. Aucun appel n’est déclenché automatiquement.'};
document.querySelectorAll('[data-human-action]').forEach(btn=>btn.addEventListener('click',()=>{const action=btn.dataset.humanAction;if(action==='urgence'){location.href='aide-urgente.html';return}humanTitle.textContent=btn.querySelector('h2').textContent;humanCopy.textContent=copyByAction[action];humanDialog.showModal()}));document.querySelectorAll('[data-dialog-close]').forEach(btn=>btn.addEventListener('click',()=>humanDialog?.close()));humanDialog?.addEventListener('click',e=>{if(e.target===humanDialog)humanDialog.close()});

// Chat demonstration and future API endpoint.
const chatForm=document.querySelector('[data-chat-form]');const chatInput=document.querySelector('[data-chat-input]');const chatThread=document.querySelector('[data-chat-thread]');const chatClear=document.querySelector('[data-chat-clear]');
const loadChat=()=>{try{return JSON.parse(localStorage.getItem(CHAT_KEY)||'[]')}catch{return []}};const saveChat=messages=>localStorage.setItem(CHAT_KEY,JSON.stringify(messages.slice(-30)));
const safeText=text=>String(text).replace(/[<>]/g,'');
const addMessage=(role,text,persist=true)=>{if(!chatThread)return;const item=document.createElement('article');item.className=`message ${role}`;item.textContent=text;const stamp=document.createElement('small');stamp.textContent=role==='assistant'?'ATLAS — aide numérique':'Vous';item.appendChild(stamp);chatThread.appendChild(item);chatThread.scrollTop=chatThread.scrollHeight;if(persist){const messages=loadChat();messages.push({role,text,at:Date.now()});saveChat(messages)}};
if(chatThread){const messages=loadChat();if(messages.length)messages.forEach(m=>addMessage(m.role,m.text,false));else addMessage('assistant','Je suis une démonstration d’ATLAS. Vous pouvez écrire ce qui vous préoccupe ; je vous aiderai à clarifier votre besoin sans poser de diagnostic.',false)}
const fallbackReply=text=>{const lower=text.toLowerCase();if(/suicid|me tuer|en finir|danger immédiat|violence/.test(lower))return 'Votre message évoque une situation qui peut nécessiter une aide immédiate. Utilisez la page « Aide urgente » ou contactez directement les services d’urgence. ATLAS ne doit pas rester votre seul soutien dans cette situation.';if(/stress|tension|angoiss|panique/.test(lower))return 'Je comprends qu’une forte tension est présente. Souhaitez-vous d’abord préciser ce qui la déclenche, ou passer directement à une respiration guidée ?';if(/triste|seul|solitude|vide/.test(lower))return 'Merci de l’avoir exprimé. Ce ressenti mérite d’être accueilli sans le minimiser. Souhaitez-vous mettre des mots sur ce qui pèse le plus, ou préparer un contact avec une personne de confiance ?';return 'Merci. Je peux vous aider à organiser ce que vous ressentez : quel est l’élément le plus difficile maintenant, et qu’attendez-vous comme soutien immédiat ?'};
const requestAI=async text=>{const response=await fetch('/api/atlas-chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:text,state:loadState(),history:loadChat().slice(-8)})});if(!response.ok)throw new Error('API indisponible');const data=await response.json();return data.reply};
chatForm?.addEventListener('submit',async event=>{event.preventDefault();const text=safeText(chatInput.value.trim());if(!text)return;addMessage('user',text);chatInput.value='';const typing=document.createElement('article');typing.className='message assistant';typing.innerHTML='<span class="typing"><i></i><i></i><i></i></span>';chatThread.appendChild(typing);chatThread.scrollTop=chatThread.scrollHeight;let reply;try{reply=await requestAI(text)}catch{reply=fallbackReply(text)}typing.remove();addMessage('assistant',reply)});
document.querySelectorAll('[data-suggestion]').forEach(btn=>btn.addEventListener('click',()=>{if(chatInput){chatInput.value=btn.dataset.suggestion;chatInput.focus()}}));chatClear?.addEventListener('click',()=>{localStorage.removeItem(CHAT_KEY);chatThread.innerHTML='';addMessage('assistant','La conversation locale a été effacée. Nous pouvons repartir de zéro.',false);showToast('Conversation supprimée de ce navigateur.')});

// Journey summary.
const setText=(selector,value)=>{const el=document.querySelector(selector);if(el)el.textContent=value};
setText('[data-summary-emotion]',state.emotion||'Non indiqué');setText('[data-summary-before]',state.emotion?`${state.intensity}/10`:'—');setText('[data-summary-after]',state.afterIntensity!=null?`${state.afterIntensity}/10`:'—');
document.querySelectorAll('[data-complete-if]').forEach(el=>{const key=el.dataset.completeIf;const complete=key==='emotion'?!!state.emotion:key==='breath'?state.completedBreath:key==='after'?state.afterIntensity!=null:!!state[key];el.classList.toggle('complete',complete)});

// Resources.
const resourceDialog=document.querySelector('[data-resource-dialog]');const resourceTitle=document.querySelector('[data-resource-title]');const resourceBody=document.querySelector('[data-resource-body]');const resourceContent={recentrage:{title:'Recentrage immédiat',body:'Regardez autour de vous et nommez cinq choses visibles, quatre sensations physiques, trois sons, deux odeurs et une chose importante pour vous maintenant. Prenez votre temps.'},decharge:{title:'Décharge mentale',body:'Écrivez pendant trois minutes sans chercher à organiser vos pensées. Ensuite, entourez uniquement ce qui demande une action aujourd’hui.'},conversation:{title:'Préparer une conversation',body:'Notez en trois lignes : ce que vous observez, ce que vous ressentez et ce dont vous avez besoin. Transformez ensuite cela en une demande concrète et réaliste.'},sommeil:{title:'Préparer le sommeil',body:'Réduisez les sollicitations, baissez la lumière et déposez sur papier les sujets à reprendre demain. Cette ressource ne remplace pas un avis médical pour des troubles persistants.'},colere:{title:'Traverser une montée de colère',body:'Éloignez-vous temporairement de la situation si cela est possible, relâchez les mains et ralentissez l’expiration. Revenez à la discussion lorsque votre niveau d’activation a baissé.'},solitude:{title:'Rompre l’isolement',body:'Choisissez une personne ou une structure et formulez une demande très simple : « Est-ce que tu peux m’appeler dix minutes aujourd’hui ? » Une demande précise est souvent plus facile à recevoir.'}};
document.querySelectorAll('[data-resource-open]').forEach(btn=>btn.addEventListener('click',()=>{const item=resourceContent[btn.dataset.resourceOpen];if(!item)return;resourceTitle.textContent=item.title;resourceBody.textContent=item.body;resourceDialog.showModal();const completed=new Set(loadState().completedResources||[]);completed.add(btn.dataset.resourceOpen);state=saveState({completedResources:[...completed]})}));document.querySelectorAll('[data-resource-close]').forEach(btn=>btn.addEventListener('click',()=>resourceDialog?.close()));document.querySelectorAll('[data-filter]').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(x=>x.classList.toggle('active',x===btn));const filter=btn.dataset.filter;document.querySelectorAll('[data-resource-card]').forEach(card=>card.hidden=filter!=='all'&&!card.dataset.category.includes(filter))}));

// Account and local data controls.
const statePreview=document.querySelector('[data-state-preview]');if(statePreview)statePreview.textContent=JSON.stringify(loadState(),null,2);
document.querySelectorAll('[data-toggle]').forEach(btn=>{const key=btn.dataset.toggle;btn.classList.toggle('active',key==='memory'?state.localMemory:state.motion==='reduced');btn.addEventListener('click',()=>{if(key==='memory')state=saveState({localMemory:!loadState().localMemory});else state=saveState({motion:loadState().motion==='reduced'?'auto':'reduced'});btn.classList.toggle('active');showToast(key==='motion'?'Le réglage prendra pleinement effet au prochain chargement.':'Préférence enregistrée localement.')})});
document.querySelector('[data-export]')?.addEventListener('click',()=>{const data={state:loadState(),chat:loadChat(),exportedAt:new Date().toISOString()};const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='atlas-donnees-locales.json';a.click();URL.revokeObjectURL(url)});
document.querySelector('[data-delete-all]')?.addEventListener('click',()=>{if(confirm('Supprimer toutes les données ATLAS enregistrées dans ce navigateur ?')){localStorage.removeItem(STORAGE_KEY);localStorage.removeItem(CHAT_KEY);showToast('Toutes les données locales ont été supprimées.');setTimeout(()=>location.reload(),700)}});

// Professional lead form demonstration.
document.querySelector('[data-professional-form]')?.addEventListener('submit',event=>{event.preventDefault();const form=new FormData(event.currentTarget);const lead=Object.fromEntries(form.entries());localStorage.setItem('atlas_professional_lead_demo',JSON.stringify({...lead,createdAt:new Date().toISOString()}));event.currentTarget.reset();showToast('Demande enregistrée localement dans cette démonstration. Aucun e-mail n’a été envoyé.')});

state=saveState({lastPage:body.dataset.page});
if('serviceWorker' in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('sw.js').catch(()=>{});
