const STORAGE_KEY='atlas_ecosystem_state_v1';
const defaults={intent:null,emotion:null,intensity:6,context:null,afterIntensity:null,completedBreath:false,lastPage:'accueil'};
const loadState=()=>{try{return {...defaults,...JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}')}}catch{return {...defaults}}};
const saveState=(patch={})=>{const next={...loadState(),...patch};localStorage.setItem(STORAGE_KEY,JSON.stringify(next));return next};
const state=loadState();
const body=document.body; const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const boot=document.querySelector('[data-boot]');
const ready=()=>setTimeout(()=>boot?.classList.add('done'),280);
if(document.readyState==='complete')ready();else addEventListener('load',ready,{once:true});setTimeout(ready,1800);

const root=document.documentElement;
addEventListener('pointermove',e=>{root.style.setProperty('--mx',`${e.clientX}px`);root.style.setProperty('--my',`${e.clientY}px`)},{passive:true});
const updateScroll=()=>{const max=Math.max(1,document.documentElement.scrollHeight-innerHeight);root.style.setProperty('--scroll',Math.min(1,scrollY/max).toFixed(4));document.querySelector('[data-header]')?.classList.toggle('scrolled',scrollY>80)};
addEventListener('scroll',updateScroll,{passive:true});updateScroll();
document.querySelector('[data-menu]')?.addEventListener('click',e=>{const h=document.querySelector('[data-header]');const open=h.classList.toggle('menu-open');e.currentTarget.setAttribute('aria-expanded',String(open))});

const revealObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting)entry.target.classList.add('visible')}),{threshold:.14,rootMargin:'0px 0px -6% 0px'});
document.querySelectorAll('.reveal').forEach(el=>revealObserver.observe(el));

const canvas=document.querySelector('[data-atlas-scene]');
if(canvas){const ctx=canvas.getContext('2d',{alpha:true});let nodes=[],raf=0,last=0,speed=1;
  const palettes={home:['79,141,125','200,162,97'],start:['79,141,125','143,199,181'],understand:['79,141,125','196,240,222'],calm:['143,199,181','225,197,141'],human:['200,162,97','242,214,170']};
  const colors=palettes[body.dataset.scene]||palettes.home;
  const resize=()=>{const dpr=Math.min(devicePixelRatio||1,1.5);canvas.width=Math.floor(innerWidth*dpr);canvas.height=Math.floor(innerHeight*dpr);canvas.style.width=`${innerWidth}px`;canvas.style.height=`${innerHeight}px`;ctx.setTransform(dpr,0,0,dpr,0,0);const count=innerWidth<700?28:Math.min(90,Math.round(innerWidth/22));nodes=Array.from({length:count},(_,i)=>({x:Math.random()*innerWidth,y:Math.random()*innerHeight,vx:(Math.random()-.5)*.16,vy:(Math.random()-.5)*.16,r:Math.random()*1.3+.3,phase:Math.random()*6.28,c:i%2}))};
  const draw=t=>{if(document.hidden||reduced)return;if(t-last<28){raf=requestAnimationFrame(draw);return}last=t;ctx.clearRect(0,0,innerWidth,innerHeight);for(let i=0;i<nodes.length;i++){const n=nodes[i];n.x+=n.vx*speed;n.y+=n.vy*speed;n.phase+=.008*speed;if(n.x<-20)n.x=innerWidth+20;if(n.x>innerWidth+20)n.x=-20;if(n.y<-20)n.y=innerHeight+20;if(n.y>innerHeight+20)n.y=-20;ctx.beginPath();ctx.arc(n.x,n.y,n.r*(1+Math.sin(n.phase)*.25),0,Math.PI*2);ctx.fillStyle=`rgba(${colors[n.c]},.34)`;ctx.fill();for(let j=i+1;j<nodes.length;j++){const m=nodes[j],dx=n.x-m.x,dy=n.y-m.y,d=Math.hypot(dx,dy);if(d<130){ctx.beginPath();ctx.moveTo(n.x,n.y);ctx.lineTo(m.x,m.y);ctx.strokeStyle=`rgba(${colors[(n.c+m.c)%2]},${(1-d/130)*.075})`;ctx.lineWidth=.55;ctx.stroke()}}}raf=requestAnimationFrame(draw)};
  resize();addEventListener('resize',resize,{passive:true});if(!reduced)raf=requestAnimationFrame(draw);
  window.atlasScene={setSpeed:v=>speed=v};
}

if(!reduced&&matchMedia('(pointer:fine)').matches){document.querySelectorAll('.magnetic').forEach(el=>{el.addEventListener('pointermove',e=>{const r=el.getBoundingClientRect();el.style.transform=`translate(${(e.clientX-r.left-r.width/2)*.08}px,${(e.clientY-r.top-r.height/2)*.08}px)`});el.addEventListener('pointerleave',()=>el.style.transform='')})}

const toast=document.querySelector('[data-toast]');let toastTimer;const showToast=msg=>{if(!toast)return;clearTimeout(toastTimer);toast.textContent=msg;toast.classList.add('visible');toastTimer=setTimeout(()=>toast.classList.remove('visible'),3200)};

document.querySelectorAll('[data-intent]').forEach(btn=>btn.addEventListener('click',()=>{const intent=btn.dataset.intent;saveState({intent,lastPage:'commencer'});if(intent==='apaiser')location.href='apaiser.html';else location.href='comprendre.html'}));

let selectedEmotion=state.emotion;let selectedContext=state.context;const intensity=document.getElementById('intensity');const intensityOutput=document.getElementById('intensity-output');const result=document.querySelector('[data-clarity-result]');const toCalm=document.querySelector('[data-to-calm]');
if(intensity){intensity.value=String(state.intensity||6);intensityOutput.textContent=`${intensity.value}/10`;intensity.addEventListener('input',()=>{intensityOutput.textContent=`${intensity.value}/10`;saveState({intensity:Number(intensity.value)})})}
const refreshClarity=()=>{document.querySelectorAll('[data-emotion]').forEach(n=>n.classList.toggle('selected',n.dataset.emotion===selectedEmotion));document.querySelectorAll('[data-context]').forEach(n=>n.classList.toggle('selected',n.dataset.context===selectedContext));if(result){result.textContent=selectedEmotion?selectedEmotion==='Je ne sais pas'?'Vous n’avez pas besoin du mot parfait. Nous pouvons commencer sans étiquette.':`Vous avez indiqué « ${selectedEmotion.toLowerCase()} »${selectedContext?` dans un contexte lié à ${selectedContext.toLowerCase()}`:''}. Souhaitez-vous d’abord diminuer son intensité ?`:'Sélectionnez un ressenti pour continuer.'}if(toCalm)toCalm.disabled=!selectedEmotion};
document.querySelectorAll('[data-emotion]').forEach(btn=>btn.addEventListener('click',()=>{selectedEmotion=btn.dataset.emotion;saveState({emotion:selectedEmotion,intensity:Number(intensity?.value||6),lastPage:'comprendre'});refreshClarity()}));
document.querySelectorAll('[data-context]').forEach(btn=>btn.addEventListener('click',()=>{selectedContext=selectedContext===btn.dataset.context?null:btn.dataset.context;saveState({context:selectedContext});refreshClarity()}));
toCalm?.addEventListener('click',()=>location.href='apaiser.html');refreshClarity();

const calmIntro=document.querySelector('[data-calm-intro]');if(calmIntro&&state.emotion){calmIntro.textContent=`Vous avez indiqué « ${state.emotion.toLowerCase()} » à ${state.intensity}/10. La lumière, les synapses et la profondeur vont maintenant suivre un rythme plus lent.`}
const breathStart=document.querySelector('[data-breath-start]');const breathCore=document.querySelector('[data-breath-core]');const breathPhase=document.querySelector('[data-breath-phase]');const breathSeconds=document.querySelector('[data-breath-seconds]');const breathCaption=document.querySelector('[data-breath-caption]');const afterCheck=document.querySelector('[data-after-check]');let remaining=60,breathing=false,timer=null,phaseTimer=null;
const stopBreath=(done=false)=>{clearInterval(timer);clearInterval(phaseTimer);timer=phaseTimer=null;breathing=false;body.classList.remove('breathing-in');window.atlasScene?.setSpeed(1);breathStart&&(breathStart.innerHTML='Lancer 60 secondes <span>→</span>');breathPhase&&(breathPhase.textContent='Prêt');breathSeconds&&(breathSeconds.textContent='60');breathCaption&&(breathCaption.textContent='Respiration cohérente');remaining=60;if(done){afterCheck.hidden=false;saveState({completedBreath:true,lastPage:'apaiser'});afterCheck.scrollIntoView({behavior:reduced?'auto':'smooth',block:'center'})}};
breathStart?.addEventListener('click',()=>{if(breathing){stopBreath();return}breathing=true;breathStart.textContent='Arrêter';window.atlasScene?.setSpeed(.35);const phases=[['Inspirez',4,true,'Laissez l’espace s’ouvrir'],['Expirez',6,false,'Relâchez sans forcer'],['Restez',2,false,'Restez simplement présent']];let i=0,elapsed=0;const setPhase=()=>{const [name,,inhale,caption]=phases[i];breathPhase.textContent=name;breathCaption.textContent=caption;body.classList.toggle('breathing-in',inhale)};setPhase();timer=setInterval(()=>{remaining--;breathSeconds.textContent=String(remaining);if(remaining<=0){stopBreath(true);showToast('Séquence terminée. Prenez un instant avant de continuer.')}},1000);phaseTimer=setInterval(()=>{elapsed++;if(elapsed>=phases[i][1]){i=(i+1)%phases.length;elapsed=0;setPhase()}},1000)});
const afterIntensity=document.getElementById('after-intensity');const afterOutput=document.getElementById('after-output');afterIntensity?.addEventListener('input',()=>afterOutput.textContent=`${afterIntensity.value}/10`);document.querySelector('[data-save-after]')?.addEventListener('click',()=>{const value=Number(afterIntensity.value);saveState({afterIntensity:value});const diff=(state.intensity||6)-value;document.querySelector('[data-after-result]').textContent=diff>0?`Vous avez déclaré une baisse de ${diff} point${diff>1?'s':''}. Vous pouvez poursuivre doucement ou rejoindre une présence humaine.`:'Votre ressenti reste présent. Le relais humain reste accessible sans terminer d’autre étape.';showToast('Ressenti enregistré localement.')});

const humanStatus=document.querySelector('[data-human-status]');if(humanStatus&&state.emotion){humanStatus.textContent=`Dernier ressenti déclaré : ${state.emotion}, ${state.intensity}/10${state.afterIntensity!=null?` puis ${state.afterIntensity}/10 après l’exercice`:''}.`}
const humanDialog=document.querySelector('[data-human-dialog]');const humanTitle=document.querySelector('[data-dialog-title]');const humanCopy=document.querySelector('[data-dialog-copy]');const copyByAction={proche:'Dans la version opérationnelle, ATLAS pourra vous aider à rédiger un message simple pour demander une présence, un appel ou un rendez-vous à une personne de confiance.',professionnel:'Cette option sera reliée à un annuaire vérifié de professionnels, avec leurs qualifications, disponibilités, zones d’intervention et conditions de prise en charge.',partenaire:'Le futur réseau ATLAS présentera clairement les structures partenaires, leurs spécialités, leurs horaires et le mode de prise de contact.',urgence:'Les ressources urgentes devront être déterminées selon le pays et la situation. Cette interface de démonstration ne déclenche actuellement aucun appel.'};
document.querySelectorAll('[data-human-action]').forEach(btn=>btn.addEventListener('click',()=>{const action=btn.dataset.humanAction;humanTitle.textContent=btn.querySelector('h2').textContent;humanCopy.textContent=copyByAction[action];humanDialog.showModal()}));document.querySelectorAll('[data-dialog-close]').forEach(btn=>btn.addEventListener('click',()=>humanDialog?.close()));humanDialog?.addEventListener('click',e=>{if(e.target===humanDialog)humanDialog.close()});

saveState({lastPage:body.dataset.page});
if('serviceWorker' in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('sw.js').catch(()=>{});
