import Link from "next/link";
import { AtlasSiteShell, SitePageHero } from "../../components/site/AtlasSiteShell";

const STEPS=[
["01","Percevoir","Le message, le contexte de session, les signaux explicites et les préférences autorisées."],
["02","Contextualiser","Relier le présent au fil récent sans transformer une hypothèse en vérité."],
["03","Délibérer","Comparer plusieurs lectures, mesurer l’incertitude et choisir une posture."],
["04","Répondre","Sélectionner la puissance de modèle adaptée et générer une réponse gouvernée."],
["05","Vérifier","Critique de sécurité, présence et adéquation émotionnelle avant livraison."],
] as const;
export default function ArchitecturePage(){return <AtlasSiteShell><SitePageHero eyebrow="ARCHITECTURE" title="Une mécanique avancée, invisible quand tout fonctionne." lead="ATLAS sépare l’intelligence conversationnelle, la sécurité, la mémoire, les outils et l’évolution. Cette séparation permet d’augmenter la puissance sans rendre le système incontrôlable." actions={<><Link className="site-primary-button" href="/conversation">Tester l’expérience</Link><Link className="site-link-button" href="/confiance">Voir les garde-fous</Link></>}/><section className="site-section"><div className="site-section-head"><p className="site-eyebrow">BOUCLE COGNITIVE</p><h2>Percevoir. Comprendre. Décider. Vérifier.</h2><p>Chaque tour traverse une chaîne structurée afin de préserver la qualité, la cohérence et la sécurité.</p></div><div className="site-steps">{STEPS.map(([n,t,p])=><article className="site-step" key={n}><span>{n}</span><strong>{t}</strong><p>{p}</p></article>)}</div></section><section className="site-section site-section-tight"><div className="site-grid"><article className="site-card site-card-feature"><span>MODEL GATEWAY</span><h3>La bonne puissance au bon moment</h3><p>ATLAS peut router un échange vers une voie rapide, équilibrée ou profonde. Le mode maximum privilégie la qualité cognitive, avec repli contrôlé si une capacité n’est pas disponible.</p></article><article className="site-card"><span>SAFETY SENTINEL</span><h3>La sécurité reste indépendante</h3><p>Les règles sensibles ne dépendent pas uniquement du modèle génératif. Les situations critiques peuvent interrompre le flux ordinaire.</p></article><article className="site-card"><span>MEMORY FABRIC</span><h3>Une mémoire gouvernée</h3><p>La cible est une mémoire inspectable, corrigible, supprimable, avec provenance et consentement explicite.</p></article><article className="site-card"><span>EVOLUTION</span><h3>Évoluer sans s’auto-déployer</h3><p>Les améliorations importantes doivent passer par évaluation, simulation, canary, validation et retour arrière.</p></article></div></section></AtlasSiteShell>}
